<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php  echo Nogometniklubovi::config('naziv');?></title>
<link rel="stylesheet" href="<?php echo Nogometniklubovi::config('url'); ?>public/css/foundation.css">
<link rel="stylesheet" href="<?php echo Nogometniklubovi::config('url'); ?>public/css/foundationicons/foundation-icons.css">
<link rel="stylesheet" href="<?php echo Nogometniklubovi::config('url'); ?>public/css/app.css">

<link rel="apple-touch-icon" sizes="192x192" href="<?php echo Nogometniklubovi::config('url'); ?>public/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo Nogometniklubovi::config('url'); ?>public/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo Nogometniklubovi::config('url'); ?>public/favicon/favicon-16x16.png">
<link rel="manifest" href="<?php echo Nogometniklubovi::config('url'); ?>public/favicon/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">