<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?php  echo Nogometniklubovi::config('naziv');?></li>
      <li><a href="<?=Nogometniklubovi::config('url') ?>">Početna stranica</a></li>
      <?php if(Nogometniklubovi::auth()): ?>
        <li><a href="<?=Nogometniklubovi::config('url') ?>nadzornaploca">Nadzorna ploča</a></li>
        <li>
          <a href="#">Glavni izbornik</a>
          <ul class="vertical menu">
            <li><a href="<?=Nogometniklubovi::config('url') ?>klub">Klubovi</a></li>
            <li><a href="<?=Nogometniklubovi::config('url') ?>igrac">Igrači</a></li>
            <li><a href="<?=Nogometniklubovi::config('url') ?>stadion">Stadioni</a></li>
            <li><a href="<?=Nogometniklubovi::config('url') ?>trener">Treneri</a></li>
          </ul>
        </li>  
      <?php endif; ?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <?php if(!Nogometniklubovi::auth()): ?>
        <li><a href="<?=Nogometniklubovi::config('url') ?>login/prijava">Prijava</a></li>
      <?php else: ?>
        <li><a href="<?=Nogometniklubovi::config('url') ?>login/odjava">Odjava</a></li>
      <?php endif; ?>
    </ul>
  </div>
</div>
